FROM ubuntu:18.04
MAINTAINER m.mohdazar45@gmail.com
RUN apt-get update
RUN apt-get install apache2 -y 
COPY . /var/www/html/
WORKDIR /var/www/html
CMD ["/usr/sbin/apache2", "-D",  "FOREGROUND"]
EXPOSE 80